### ISSUE TITLE
how to reproduce neff values for the grating coupler example?

### ISSUE THREAD

**Issue by joamatab** [anstmichaels/emopt#14]
wavelength = 1.55
    h_wg = 0.28
    h_etch = 0.19
    neff = 2.8548
    neff_etched = 2.0879

is the top cladding air or oxide?
what waveguide width do you assume?

**Comment by anstmichaels** [comment]
Hmm, good question. The neff should be calculated based on the same simulation parameters as are used in the optimization (waveguide thickness = 280 nm, top and bottom cladding = oxide).

As far as waveguide width goes, we assume that the grating is sufficiently wide that it can be modeled as silicon in 2D.
