### ISSUE TITLE
install.py pulls incompatible versions of petsc and slepc

### ISSUE THREAD

**Issue by sbyrnes321** [anstmichaels/emopt#5]
The install.py script is currently set to download slepc version 3.9.1 (explicitly), and the latest maint branch of petsc, which (as of this writing) is 3.10. Unfortunately, these two are incompatible!

http://slepc.upv.es/download/changes.htm

It's probably just a matter of editing the petsc download link to get a specific version ... the link is somewhere on this page I think: https://www.mcs.anl.gov/petsc/download/index.html

Thanks in advance! --Steve

**Comment by anstmichaels** [comment]
I just pushed a change which updated the SLEPc version in install.py. Give that a try and let me know if it works now.

At some point I will try to find a better way to maintain the correct versions of all of these different packages. For now, install.py should be treated as a mostly working aid for installing the dependencies.

**Comment by sbyrnes321** [comment]
Well, at least for now, that fixes it, thanks!
